/** {path => excerpt} */
postInfo = {'p/dynamic_dom_viewer' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/dynamic_dom_viewer" rel="bookmark">Dynamic DOM Viewer</a></h2> </header> <div class="entry-summary"><p>A handy JavaScript tool. I have worked with JavaScript on numerous web-based projects for dynamic client-side functionality. Quite often I found that I needed to write a little script to expose a JavaScript object’s member functions and properties [&hellip;]</p></div></article>',
'p/find_jars_perl_version' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/find_jars_perl_version" rel="bookmark">Find Jars – Perl Version</a></h2> </header> <div class="entry-summary"><p>A number of years ago I wrote this little utility script in Perl. It’s handy during Java development when you need to locate a particular jar file, but don’t know which one exactly. [&hellip;]</p></div> </article>',
'p/jarfind' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/jarfind" rel="bookmark">JarFind</a></h2> </header> <div class="entry-summary"><p>JarFind is a Java development tool. It’s purpose is to quickly find jar files which contain a particular Java .class file. [&hellip;]</p></div> </article>',
'p/javadoc_viewer' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/javadoc_viewer" rel="bookmark">Javadoc Viewer</a></h2> </header> <div class="entry-summary"><p>Javadoc Viewer is an enhanced Web UI for viewing Javadoc pages. It provides a number of features which help the Java developer work with Javadocs more efficiently and productively. [&hellip;]</p></div> </article>',
'p/jdbc_framework' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/jdbc_framework" rel="bookmark">JDBC Framework</a></h2> </header> <div class="entry-summary"><p>Why a JDBC framework? My aim in developing a JDBC framework was to create a simple, flexible, and lightweight framework for running JDBC queries. [&hellip;]</p></div> </article>',
'p/jdbc_testing_with_mock_objects' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/jdbc_testing_with_mock_objects" rel="bookmark">JDBC Testing With Mock Objects</a></h2> </header> <div class="entry-summary"><p>Not long ago I had to design a testing strategy for JDBC code. As I began prototyping I ran into the problem of corrupt data from the database. [&hellip;]</p></div> </article>',
'p/web_services_part_1' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/web_services_part_1" rel="bookmark">Web Services – Part 1</a></h2> </header> <div class="entry-summary"><p>For a Web Service demo I decided to create a simple service with a few methods that would provide access to data that I had been using for my Message Editor application. [&hellip;]</p></div> </article>',
'p/web_services_part_2' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/web_services_part_2" rel="bookmark">Web Services – Part 2</a></h2> </header> <div class="entry-summary"><p>Perl Implementation: The SOAP::Lite module does most of the heavy lifting. Consider this example[&hellip;]</p></div> </article>',
'p/web_services_part_3' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/web_services_part_3" rel="bookmark">Web Services – Part 3</a></h2> </header> <div class="entry-summary"><p>Axis2 Implementation: I implemented the Axis2 version of my web service in the usual way using the code generation tools that come with the Axis2 distribution – java2wsdl.bat and wsdl2java.bat. [&hellip;]</p></div> </article>',
'p/web_services_part_4' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/web_services_part_4" rel="bookmark">Web Services – Part 4</a></h2> </header> <div class="entry-summary"><p>RESTful Implementation: The RESTful version was probably the easiest to implement. I used the JAX-RS/Jersey API to create the service as well as a test client. [&hellip;]</p></div> </article>',
'p/xslt_for_dynamic_content_generation' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/xslt_for_dynamic_content_generation" rel="bookmark">XSLT For Dynamic Content Generation</a></h2> </header> <div class="entry-summary"><p>A number of years ago I came across an article, “XSLT Querying & XML Documents,” by Giuseppe Naccarato, in Dr.Dobb’s Journal, December 2002. In this article Mr. Naccarato described a relatively new use of XSLT [&hellip;]</p></div> </article>',
'p/xslt_with_jstl' : '<article class="post type-post status-publish format-standard hentry category-jsp category-jstl category-xslt clearfix"> <header class="entry-header"> <h2 class="entry-title"><a href="p/xslt_with_jstl" rel="bookmark">XSLT With JSTL</a></h2> </header> <div class="entry-summary"><p>XSLT has a variety of advantages and is suitable for a number of tasks that would be more tedious otherwise. XSLT can also be used in conjunction with JSTL tags, as well, to produce consistent and reusable HTML elements. [&hellip;]</p></div> </article>'}
