#Error Message Properties File - www.achex.com.
#Wed Aug 29 00:32:26 PDT 2001
ACCOUNT_LOCKED=Your account has been locked. Please contact customer care at <CUSTOMER_SUPPORT_PHONE_NUM> (between 6 am and 6 pm PST), or email <GENERAL_CUST_SERVICE_FROM>.
BUSINESSPOSTALCODE_REQ=Please enter a ZIP Code for your Business.
ROUTINGNUMBER_INVALID=Please enter a valid 9 digit bank routing number
EMAIL_REQ=Please enter your email address.
DAILY_PAYMENTS_EXCEEDED=You have reached your current Achex limit for the maximum number of transactions within a 24-hour period.
NEWPASSWORD_REQ=Please enter a new password before continuing.
RISKWISE_MISKEYED_INFO=Information in your application has been miskeyed. There may be several contributing factors, including\: your name, address, home phone number, or Social Security number.  Please verify that all information is correct and submit again.
ADMINDEPT_REQ=Please enter an Administrator Department.
EVENINGPHONE_INVALID=Please enter a valid home telephone number.
MIDDLEINITIAL_INVALID=Please enter a valid Middle Initial.
BUSINESSALIAS_INVALID=Please enter a valid Business Alias. Your Business Alias cannot contain the quote (") character.
BANK_INFO_RESUBMIT=Our systems indicate that you may have entered your checking account number incorrectly. Please examine the account number you entered in the Achex registration form. If it is incorrect, enter your correct checking account number and submit your registration again. If you need help, please contact Achex Customer Care.
FIRSTNAME_REQ=Please enter a First name.
MONTHLY_CLAIM_LIMIT_EXCEEDED=You have exceeded your monthly payment receipt limit of $5000.  If you expect to exceed your monthly payment limit regularly, you should register as a Merchant by contacting Achex Business Development at Businessdevelopment@achex.com.
CHECK_VOIDED=This payment has been voided by the sender.
USERNAME_REQ=Please enter a User Name.
CHECKING_ACCOUNT_SEND_DISABLED=Your Achex account has been disabled.
SECRET_ANSWER_INVALID=Either the information submitted as the answer to the secret question, or the information submitted as your Social Security number, was incorrect. Please try again.
CHANGE_PWD_CONFIRM_ERROR=The password entered in the 'New Password' field did not match the password entered in the 'Confirm Password' field. Please try again.
PASSWORD_INVALID=Your password must contain at least six characters.  Please try a new password.
SOCSECNUM_INVALID=Please enter a valid Social Security number.
BANKSTATE_REQ=Please select the state in which your bank is located.
CHECK_EXPIRED=The payment that you are attempting to claim has expired.
LASTNAME_REQ=Please enter a Last Name.
POS_ACCOUNT_DISABLED=Your account has been disabled. Please contact Achex Customer Care at <CUSTOMER_SUPPORT_PHONE_NUM> between 6 a.m. and 6 p.m. Pacific Time to reinstate your account.
SINGLE_PAYMENT_AMOUNT_EXCEEDED=The amount you entered exceeds your current Achex single-transaction limit.
BUSINESSSTREET2_INVALID=Please enter a valid street address for your business (Business Address Line 2).
FORCE_PASSWORD_CHANGE_ISSUE_PAYMENT=You must change your password before you can issue this payment. Please change your password, then attempt to issue your payment again.
ACCOUNT_CLOSED=Your account has been closed.
ADMINTITLE_INVALID=Please enter a valid Administrator Title.
EMAIL_INVALID=Please enter a valid Email 
REQUEST_ID_INVALID=This request for payment is formatted improperly. Please try either clicking the link again, or cutting and pasting the link into your browser's address line.
BANKNAME_INVALID=Please enter a valid Bank Name.
FORCE_PASSWORD_CHANGE=You must change your password before you can cancel this payment. Please change your password, then attempt to cancel your payment again.
ACCOUNT_ERROR_END=Please contact Customer Care at <CUSTOMER_SUPPORT_PHONE_NUM>.
FIRST_NAME_REQ=Please enter a first name for the recipient of your request.
CONTACTNUMBER_REQ=Please enter a Contact Phone Number
BUSINESSSTREET1_REQ=Please enter a Street Address for your Business.
STATE_INVALID=Please select a valid state for your address.
SOCSECNUM_REQ=Please enter your Social Security number.
DAILY_CLAIM_LIMIT_EXCEEDED=You have exceeded your daily payment receipt limit of $2000.  If you expect to exceed your monthly payment limit regularly, you should register as a Merchant by contacting Achex Business Development at Businessdevelopment@achex.com.
CHECKINGACCOUNTNUM_INVALID=Please enter a valid Checking Account Number
BUSINESSNAME_INVALID=Please enter a valid Business Name. Your Business Name cannot contain the quote (") character.
RECEMAIL_REQ=Please provide recipient's email address.
REQUEST_PAYMENT_INFORMATION_NOT_FOUND=The information for this request for payment could not be found. Please try either clicking the link again, or cutting and pasting the link into your browser's address line.
BANK_INFO_REJECTED_NOT_ACHABLE=Our systems indicate that you may have entered your checking account information incorrectly. We recommend that you reenter your checking account information in the Achex registration form, then resubmit your registration. It is also possible that your bank does not allow electronic fund transfers through ACH, or that your bank has an alternate account number for your use. Please contact your bank or Achex Customer Care.
AUTH_FAILED=The user name / password combination you entered was not found in our system. Please try again.
BUSINESSPOSTALCODE_INVALID=Please enter a valid ZIP Code for your Business.
LASTNAME_INVALID=Please enter a valid Last Name.
EXCEEDS_MAX_REQUEST_PAYMENT_LIMIT=Your request for payment can not exceed $500.00
SSN_ALREADY_EXISTS=You are already an existing Achex customer. Please log in to access your account.
USER_NAME_ALREADY_EXISTS=This user name has already been taken. Please enter a new user name.
PASSWORD_REQ=Please enter a password.
MONTHLY_AMOUNT_EXCEEDED=The amount you entered exceeds your current Achex transaction limit
CHECK_NOT_FOUND=The payment that you are attempting to claim could not be found. Please contact the sender and/or Customer Care for assistance.
BUSINESSCOUNTRY_REQ=Please select a Country for your Business.
EMAIL_MESSAGE_TOO_LONG=Your message is allowed to be a maximum of 500 characters in length.
CITY_INVALID=Please enter a valid City 
OLDPASSWORD_REQ=Please enter your current password.
STREET2_INVALID=Please enter a valid Address (Home Address Line 2).
BANK_INFO_REJECTED_OTHER=We were not able to verify your checking account information. Please review the information you entered in the Achex registration form to ensure that all information is correct, then resubmit your registration. If you need help, please contact Achex Customer Care.
BUSINESSMAINPHONE_REQ=Please enter a Main Phone Number for your Business.
SYSTEM_NOT_AVAILABLE=The system is temporarily unavailable. Please try again later.
BUSINESSCOUNTRY_INVALID=Please select a Country for your Business.
DAYPHONE_REQ=Please enter your contact phone number.
THOMPSON_ERROR=We could not verify your bank account information. Please ensure that all information is correct, then resubmit your registration.
SUBJECT_TOO_LONG=Your subject line is allowed to be a maximum of 75 characters in length.
AUTH_PASSWORD_REQ=Please enter a password.
NEW_PWD_ERROR=Your new password must contain at least six characters. Please enter a different password.
CHANGE_PWD_LIMIT_WARNING_2=more attempts before your account is disabled.
CHANGE_PWD_LIMIT_WARNING_1=You are allowed 
RISKWISE_VERIFY_FAILED=We are unable to verify your identity at this time. There may be several contributing factors, including\: a recent name change, a recent change of address, the use of a phone number other than your home phone number in our home phone number field, or miskeying of your Social Security number. Please verify that all information is correct and submit again.
RECP_ALL_BLANK=Please enter either the Recipient's first and last name, or a business name.
BUSINESSCITY_REQ=Please enter a City for your Business.
POS_TRANSACTION_ERROR=Your transaction cannot be processed at this time.  Please contact this merchant's Customer Support.
ACCOUNT_DISABLED=Your account has been disabled.
RECP_BOTH=Payment cannot be sent to both an individual and a business. Please enter either the Recipient's first and last name, or a business name.
POSTALCODE_REQ=Please enter a ZIP Code.
POS_ACCOUNT_LOCKED=Your account has been locked. Please contact Achex Customer Care at <CUSTOMER_SUPPORT_PHONE_NUM> between 6 a.m. and 6 p.m. Pacific Time to reinstate your account.
POS_SESSION_EXPIRED=Your session has expired.
CLAIM_URL_MODIFIED=The Payment URL has been modified. This result has been logged for security purposes.
RECLASTNAME_REQ=Please provide recipient's last name.
PASSWORD_FAILED=The password you entered cannot be validated. Please reenter your password and resubmit.
CHECKING_ACCOUNT_SEND_RECEIVE_DISABLED=Your Achex account has been disabled.
BANKSTATE_INVALID=Please select a valid state for your bank.
DUNSNUMBER_INVALID=Please enter either a valid DUNS Number or a valid EIN Number for your business.  Your DUNS Number must contain 9 digits.
SECRETQUESTION_REQ=Please enter your secret question.
FIRSTNAME_INVALID=Please enter a valid First Name.
BANKCITY_REQ=Please enter the city in which your bank is located.
ADMINTITLE_REQ=Please enter an Administrator Title.
CHECKINGACCOUNTNUM_REQ=Please enter your Checking Account Number.
DAYPHONE_INVALID=Please enter a valid Contact Phone Number
DUNS_EIN_BOTH_BLANK=Please enter either an EIN Number or a DUNS Number.
ACCOUNT_ALREADY_REGISTERED=This bank account is already Achex-enabled. Please sign in with your user name and password to access your My Achex page.
USERNAME_INVALID=User Name must contain between four and twenty characters. In addition, the first character must be a letter or a number.  Please enter a new User Name.
STREET1_REQ=Please enter an Address.
VERIFY_PASSWORD_MISMATCH=We are unable to match the password entered in the original field with the password entered in the confirming field. Please try again.
BUSINESSNAME_REQ=Please enter a Business Name.
BUSINESSSTREET1_INVALID=Please enter a valid street address for your business (Business Address Line 1).
CHECKING_ACCOUNT_CLOSED=Your Achex account has been closed.
BUSINESSSTATE_INVALID=Please select a State for your Business.
MIN_PAYMENT_LIMIT=A single Achex transaction must be at least <MINIMUM_PAYMENT_AMOUNT>.
EVENINGPHONE_REQ=Please enter your home telephone number.
EIN_INVALID=Please enter either a valid EIN Number or DUNS Number for your business.  Your EIN Number must contain 9 digits.
SIGNUP_RETRY_LIMIT_EXCEEDED=You have exceeded the maximum number of retry attempts for user registration.
DAILY_AMOUNT_EXCEEDED=You have reached your current Achex daily transaction limit.
POSTALCODE_INVALID=Please enter a valid ZIP Code
AMOUNT_INVALID=Information for the amount field is incorrect.  Please enter the amount using this format\: \#\#\#.\#\#
ADMINDEPT_INVALID=Please enter a valid Administrator Department.
AMOUNT_REQ=Please provide a payment amount.
SENDER_ACCOUNT_DISABLED=The sender's account has been disabled.
BUSINESSMAINPHONE_INVALID=Please enter a valid Main Phone Number for your Business.
SESSION_TIMED_OUT=You have been automatically logged out of your account as a security precaution because of the length of time you've been inactive since you signed in. To continue with your task, please sign in below.
LAST_NAME_REQ=Please enter a last name for the recipient of your request.
USERNAME_NOT_FOUND=The user name you entered could not be found. Please try again.
SICCODE_REQ=Please select a business type category and subcategory.
AUTH_LIMIT_WARNING_2=\ more attempts before your account is locked.
AUTH_LIMIT_WARNING_1=You are allowed 
RETRY_WARNING=Warning\: You may only fail the authorization process a total of <NUM_ATTEMPTS_ALLOWED> times. After that, your account will be disabled for 24 hours.
ACCOUNT_ERROR_BEGIN=Your request cannot be completed at this time for the following reason\:
RECFIRSTNAME_REQ=Please provide recipient's first name.
POS_ACCOUNT_CLOSED=Your account has been closed. Please contact Achex Customer Care at <CUSTOMER_SUPPORT_PHONE_NUM> between 6 a.m. and 6 p.m. Pacific Time to reinstate your account.\r\n
SECRETANSWER_REQ=Please enter your secret answer.
BIZ_NAME_REQ=Please enter a business name for the recipient of your request.
CITY_REQ=Please enter a City.
POS_CHANGE_PASSWORD=You must change your password. Please visit www.achex.com and create a new password for this account.
CHANGE_PWD_ERROR=The password you entered was not found in our system. Please enter your current password.
STREET1_INVALID=Please enter a valid Address (Home Address Line 1).
CHECK_ALREADY_CLAIMED=The payment that you are attempting to claim has already been claimed. A payment can only be claimed once.
BUSINESSCITY_INVALID=Please enter a valid City for your Business.
SECURITY_VIOLATION=The user authorizing this transaction must be the same as the currently signed-in user.
CLAIM_IDENTITY_FAILURE=You may not be the intended recipient of this payment. Please contact the sender and confirm that your name was spelled correctly.
CONTACTNUMBER_INVALID=Please enter a valid Contact Phone Number.
BANKNAME_REQ=Please enter the name of your bank
EMAIL_ADDRESS_INVALID=Please enter a valid email address for the recipient of your request.
RECEMAIL_INVALID=Please enter a valid email address.
NEWPASSWORDCONFIRM_REQ=Please confirm your new password before continuing.
